// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       int32
	Name     string
	ParentID pgtype.Int4
}

type Inventory struct {
	ID            int32
	VariantID     pgtype.Int4
	Stock         int32
	ReservedStock int32
	UpdatedAt     pgtype.Timestamp
}

type InventoryMovement struct {
	ID           int32
	VariantID    pgtype.Int4
	UserID       pgtype.UUID
	MovementType pgtype.Text
	Quantity     int32
	Reference    pgtype.Text
	Reason       pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type Order struct {
	ID                      pgtype.UUID
	CustomerID              pgtype.UUID
	ShippingAddressID       pgtype.Int4
	Status                  pgtype.Text
	TotalAmount             pgtype.Numeric
	ShippingAddressSnapshot string
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
}

type OrderItem struct {
	ID        int32
	OrderID   pgtype.UUID
	VariantID pgtype.Int4
	Quantity  int32
	UnitPrice pgtype.Numeric
	Subtotal  pgtype.Numeric
}

type Payment struct {
	ID             pgtype.UUID
	OrderID        pgtype.UUID
	Provider       pgtype.Text
	TransactionRef pgtype.Text
	Amount         pgtype.Numeric
	Status         pgtype.Text
	CreatedAt      pgtype.Timestamp
}

type Product struct {
	ID          int32
	CategoryID  pgtype.Int4
	Name        string
	Description pgtype.Text
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamp
}

type ProductImage struct {
	ID           int32
	ProductID    pgtype.Int4
	ImageUrl     string
	IsPrimary    pgtype.Bool
	DisplayOrder pgtype.Int4
	CreatedAt    pgtype.Timestamp
}

type ProductVariant struct {
	ID            int32
	ProductID     pgtype.Int4
	Sku           string
	Attributes    []byte
	Price         pgtype.Numeric
	MinStockAlert int32
}

type Promotion struct {
	ID            int32
	Code          string
	DiscountType  pgtype.Text
	DiscountValue pgtype.Numeric
	ValidFrom     pgtype.Timestamp
	ValidUntil    pgtype.Timestamp
	IsActive      pgtype.Bool
}

type Return struct {
	ID           int32
	OrderID      pgtype.UUID
	VariantID    pgtype.Int4
	Quantity     int32
	Reason       pgtype.Text
	Status       pgtype.Text
	RefundAmount pgtype.Numeric
	CreatedAt    pgtype.Timestamp
}

type Role struct {
	ID          int32
	Name        string
	Permissions []byte
}

type User struct {
	ID           pgtype.UUID
	RoleID       pgtype.Int4
	Name         string
	Email        string
	PasswordHash string
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamp
}

type UserAddress struct {
	ID            int32
	UserID        pgtype.UUID
	Title         string
	StreetAddress string
	City          string
	StateProvince string
	PostalCode    pgtype.Text
	Country       string
	PhoneContact  pgtype.Text
	IsDefault     pgtype.Bool
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamp
}
