// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getProducts = `-- name: GetProducts :one
SELECT id, category_id, name, description, is_active, created_at FROM products
`

func (q *Queries) GetProducts(ctx context.Context) (Product, error) {
	row := q.db.QueryRow(ctx, getProducts)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
